defaultDomainConfig:
  defaultRateLimitConfig:
    rateLimit: 50
    timeWindowInSeconds: 60

domainConfig:
  google.com:
    defaultRateLimitConfig:    # Default rate limit for this domain
      rateLimit: 100
      timeWindowInSeconds: 60
    apiConfig:
      /search:
        rateLimitConfig:
          rateLimit: 100        # Specific rate limit for the /search API
          timeWindowInSeconds: 60
        tags: []
      /maps:
        rateLimitConfig:
          rateLimit: 100        # Specific rate limit for the /maps API
          timeWindowInSeconds: 60
        tags: []

  facebook.com:
    defaultRateLimitConfig:    # Default rate limit for this domain
      rateLimit: 100
      timeWindowInSeconds: 60
    apiConfig:
      /search:
        rateLimitConfig:
          rateLimit: 200        # Specific rate limit for the /search API
          timeWindowInSeconds: 60
        tags: []
      /maps:
        rateLimitConfig:
          rateLimit: 200        # Specific rate limit for the /maps API
          timeWindowInSeconds: 60
        tags: []

batchProcessingConfig:
  batchSize: 100
  threadPoolSize: 10
