name: Java CI Pipeline

on: [push, pull_request]

jobs:
  build_job:

    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2
          
      # Step 2: Set up Java environment (Java 17 as per your pom.xml)
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      # Step 3: Cache Maven dependencies
      - name: Maven Packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build the project
      - name: Build with Maven and run tests
        run: mvn clean install

      # Step 5: Run Test
      - name: Run tests
        run: mvn test


      # Step 6: Report Test
      - name: Archive test reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports/