name: Java CI Pipeline

on: [push, pull_request]

jobs:
  build_job:

    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2
          
      # Step 2: Set up Java environment (Java 17 as per your pom.xml)
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      # Step 3: Cache Maven dependencies
      - name: Maven Packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build Project
      - name: Build with Maven
        run: mvn clean install
        
      # Step 5: Run Test Cases
      - name: Run Tests with JaCoCo
        run: mvn test

      - name: Generate JaCoCo Coverage Report
        run: mvn jacoco:report

      - name: Upload JaCoCo Report as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: target/site/jacoco/

      - name: Upload JaCoCo Coverage XML
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-coverage-xml
          path: target/site/jacoco/jacoco.xml